/**
 * Indicatieve LwA-waarden (geluidsvermogen, EN 12102) van courante
 * lucht/water-buitenunits op de Belgische markt.
 * Bron: fabrikantfiches / productliteratuur, nominaal of opgegeven max.
 * Werkpunt, toerental en meetafstand wijzigen het resultaat — altijd toetsen.
 */
window.REDUCD_VLAREM_PUMPS = [
  { brand: "Daikin", model: "Altherma 3 M EBLA04EV", lwa: 58 },
  { brand: "Daikin", model: "Altherma 3 M EBLA06EV", lwa: 60 },
  { brand: "Daikin", model: "Altherma 3 M EBLA08EV", lwa: 62 },
  { brand: "Daikin", model: "Altherma 3 H HT EPRA08DW1", lwa: 62 },
  { brand: "Daikin", model: "Altherma 3 H HT EPRA10DW1", lwa: 64 },
  { brand: "Daikin", model: "Altherma 3 H HT EPRA14DW1", lwa: 67 },
  { brand: "Daikin", model: "Altherma 3 H HT EPRA16DW1", lwa: 69 },
  { brand: "Daikin", model: "Altherma 3 R ERLA11DV", lwa: 64 },
  { brand: "Daikin", model: "Altherma 3 R ERLA14DV", lwa: 67 },
  { brand: "Daikin", model: "Altherma 3 R ERLA16DV", lwa: 68 },
  { brand: "Vaillant", model: "aroTHERM plus VWL 35/6 A", lwa: 54 },
  { brand: "Vaillant", model: "aroTHERM plus VWL 55/6 A", lwa: 58 },
  { brand: "Vaillant", model: "aroTHERM plus VWL 75/6 A", lwa: 60 },
  { brand: "Vaillant", model: "aroTHERM plus VWL 105/6 A", lwa: 63 },
  { brand: "Vaillant", model: "aroTHERM plus VWL 125/6 A", lwa: 65 },
  { brand: "Vaillant", model: "aroTHERM VWL 85/5 AS", lwa: 61 },
  { brand: "Mitsubishi Electric", model: "Ecodan PUHZ-SW50VAA", lwa: 61 },
  { brand: "Mitsubishi Electric", model: "Ecodan PUHZ-SW75VAA", lwa: 64 },
  { brand: "Mitsubishi Electric", model: "Ecodan PUHZ-SW100VAA", lwa: 66 },
  { brand: "Mitsubishi Electric", model: "Ecodan PUHZ-SW120VAA", lwa: 68 },
  { brand: "Mitsubishi Electric", model: "Ecodan PUZ-WM60VHA", lwa: 60 },
  { brand: "Mitsubishi Electric", model: "Ecodan PUZ-WM85VHA", lwa: 63 },
  { brand: "Panasonic", model: "Aquarea High Performance 5 kW (WH-UDZ05)", lwa: 59 },
  { brand: "Panasonic", model: "Aquarea High Performance 7 kW (WH-UDZ07)", lwa: 61 },
  { brand: "Panasonic", model: "Aquarea High Performance 9 kW (WH-UDZ09)", lwa: 64 },
  { brand: "Panasonic", model: "Aquarea T-CAP 9 kW (WH-UXZ09)", lwa: 64 },
  { brand: "Panasonic", model: "Aquarea T-CAP 12 kW (WH-UXZ12)", lwa: 68 },
  { brand: "Panasonic", model: "Aquarea T-CAP 16 kW (WH-UXZ16)", lwa: 70 },
  { brand: "LG", model: "Therma V R32 Monobloc 5 kW", lwa: 60 },
  { brand: "LG", model: "Therma V R32 Monobloc 7 kW", lwa: 63 },
  { brand: "LG", model: "Therma V R32 Monobloc 9 kW", lwa: 65 },
  { brand: "LG", model: "Therma V R32 Monobloc 12 kW", lwa: 67 },
  { brand: "LG", model: "Therma V R32 Monobloc 16 kW", lwa: 69 },
  { brand: "Samsung", model: "EHS Mono R32 5 kW (AE050CXYDEK)", lwa: 61 },
  { brand: "Samsung", model: "EHS Mono R32 8 kW (AE080CXYDEK)", lwa: 63 },
  { brand: "Samsung", model: "EHS Mono R32 12 kW (AE120CXYDEK)", lwa: 67 },
  { brand: "Samsung", model: "EHS Mono R32 16 kW (AE160CXYDEK)", lwa: 69 },
  { brand: "Bosch", model: "Compress 5800i AW 5", lwa: 55 },
  { brand: "Bosch", model: "Compress 5800i AW 7", lwa: 58 },
  { brand: "Bosch", model: "Compress 5800i AW 10", lwa: 61 },
  { brand: "Bosch", model: "Compress 6800i AW 12", lwa: 64 },
  { brand: "Bosch", model: "Compress 6800i AW 17", lwa: 67 },
  { brand: "Viessmann", model: "Vitocal 250-A 7.0", lwa: 56 },
  { brand: "Viessmann", model: "Vitocal 250-A 10.0", lwa: 59 },
  { brand: "Viessmann", model: "Vitocal 250-A 13.0", lwa: 64 },
  { brand: "Viessmann", model: "Vitocal 222-A 8 kW", lwa: 58 },
  { brand: "NIBE", model: "F2120-8", lwa: 54 },
  { brand: "NIBE", model: "F2120-12", lwa: 58 },
  { brand: "NIBE", model: "F2120-16", lwa: 61 },
  { brand: "NIBE", model: "F2120-20", lwa: 63 },
  { brand: "NIBE", model: "S2125-8", lwa: 52 },
  { brand: "NIBE", model: "S2125-12", lwa: 56 },
  { brand: "Atlantic", model: "Extensa AI 5", lwa: 60 },
  { brand: "Atlantic", model: "Extensa AI 8", lwa: 63 },
  { brand: "Atlantic", model: "Extensa AI 11", lwa: 66 },
  { brand: "Atlantic", model: "Alfea Extensa A.I. 14", lwa: 68 },
  { brand: "Toshiba", model: "Estia 6 kW (HWS-P805XWHM3-E)", lwa: 62 },
  { brand: "Toshiba", model: "Estia 8 kW", lwa: 64 },
  { brand: "Toshiba", model: "Estia 11 kW", lwa: 66 },
  { brand: "Toshiba", model: "Estia 14 kW", lwa: 68 },
  { brand: "Hitachi", model: "Yutaki M 6.0", lwa: 61 },
  { brand: "Hitachi", model: "Yutaki M 8.0", lwa: 63 },
  { brand: "Hitachi", model: "Yutaki M 11.0", lwa: 65 },
  { brand: "Hitachi", model: "Yutaki S80 10 kW", lwa: 64 },
  { brand: "Fujitsu", model: "Waterstage Comfort 6", lwa: 60 },
  { brand: "Fujitsu", model: "Waterstage Comfort 8", lwa: 62 },
  { brand: "Fujitsu", model: "Waterstage Comfort 10", lwa: 64 },
  { brand: "Fujitsu", model: "Waterstage High Power 14", lwa: 68 },
  { brand: "Alpha Innotec", model: "LWDV 51-1/3", lwa: 52 },
  { brand: "Alpha Innotec", model: "LWDV 81-1/3", lwa: 54 },
  { brand: "Alpha Innotec", model: "LWDV 91-1/3", lwa: 55 },
  { brand: "Alpha Innotec", model: "LWDV 121-1/3", lwa: 58 },
  { brand: "Stiebel Eltron", model: "WPL 15 ACS", lwa: 56 },
  { brand: "Stiebel Eltron", model: "WPL 20 ACS", lwa: 58 },
  { brand: "Stiebel Eltron", model: "WPL 25 A", lwa: 61 },
  { brand: "Stiebel Eltron", model: "WPL 07 ACS classic", lwa: 54 },
  { brand: "Weishaupt", model: "WWP L 8 IDB", lwa: 57 },
  { brand: "Weishaupt", model: "WWP L 11 IDB", lwa: 60 },
  { brand: "Weishaupt", model: "WWP L 15 IDB", lwa: 63 },
  { brand: "Remeha", model: "Elga Ace 4 kW", lwa: 58 },
  { brand: "Remeha", model: "Elga Ace 6 kW", lwa: 61 },
  { brand: "Remeha", model: "Mercuria 8", lwa: 62 },
  { brand: "Intergas", model: "Xtreme 28", lwa: 58 },
  { brand: "Intergas", model: "Xtreme 36", lwa: 59 },
  { brand: "CTC", model: "EcoAir 610M", lwa: 55 },
  { brand: "CTC", model: "EcoAir 614M", lwa: 58 },
  { brand: "CTC", model: "EcoAir 622M", lwa: 62 },
  { brand: "IVT", model: "Air X 90", lwa: 56 },
  { brand: "IVT", model: "Air X 110", lwa: 59 },
  { brand: "Thermia", model: "Atec 9", lwa: 57 },
  { brand: "Thermia", model: "Atec 13", lwa: 61 },
  { brand: "Ochsner", model: "AIR 85 C12A", lwa: 53 },
  { brand: "Ochsner", model: "AIR 11 C12A", lwa: 56 },
  { brand: "Dimplex", model: "LA 9TU", lwa: 58 },
  { brand: "Dimplex", model: "LA 12TU", lwa: 61 },
  { brand: "Wolf", model: "CHA-10/400V", lwa: 57 },
  { brand: "Wolf", model: "BWL-1S-10", lwa: 60 },
  { brand: "Buderus", model: "Logatherm WLW196 i-6 AR", lwa: 56 },
  { brand: "Buderus", model: "Logatherm WLW196 i-10 AR", lwa: 61 },
  { brand: "Junkers Bosch", model: "Supraeco A WW 8", lwa: 59 },
  { brand: "Inventum", model: "Modul-Air All-E 4.5", lwa: 57 },
  { brand: "Itho Daalderop", model: "HP-M 55", lwa: 58 },
  { brand: "Itho Daalderop", model: "HP-M 75", lwa: 61 },
  { brand: "Clivet", model: "ELFOEnergy Edge EVO 2.1 7", lwa: 60 },
  { brand: "Midea", model: "M-Thermal Mono 6 kW", lwa: 60 },
  { brand: "Midea", model: "M-Thermal Mono 10 kW", lwa: 64 },
  { brand: "Gree", model: "Versati III 8 kW", lwa: 62 },
  { brand: "Gree", model: "Versati III 12 kW", lwa: 66 },
  { brand: "Haier", model: "Super Aqua 8 kW", lwa: 61 },
  { brand: "Glow-worm", model: "AroTHERM plus 7 kW", lwa: 60 }
];
